### ISSUE TITLE
Expand the Config File Structure to Support Multiple Features

### ISSUE THREAD

**Issue by hrtsegv** [knbr13/watcher#8]
currently the config file structure is too basic:
```yaml
event-name:
 - command 1
 - command 2
```

it could be updated to:

```yaml
event-name:
 - patern (to filter files)
   commands (list of commands to run)
   mode (running commands sequentially or in parallel)
   on_success (command to run in case the main command/s has been executed successfully)
   on_failure (command to run in case the main command/s has failed)
   timeout (a timeout value for the command/s)
```

an example of the new structure:

```yaml
# Watch a Go project, rebuild on change, deploy to Kubernetes on success
write:
  - pattern: "**/*.go"
    commands:
      - "go build -o ./bin/app"
      - "kubectl rollout restart deployment/app"
    mode: "sequence"
    timeout: "2m"
    on_success: "echo 'Deployed to Kubernetes!' | slackcat"
    on_failure: "notify-send 'Build failed!'"
```

after expanding the config structure, adding new config value will be easy.
